import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter_session_manager/flutter_session_manager.dart';
import 'package:http/http.dart' as http;
import 'package:online_fruits_and_vegetables_app/utils/Endpoints.dart';

import '../models/CustomerModel.dart';
import '../models/ProductModel.dart';
import '../models/categories.dart';
import '../models/login_response.dart';
import '../models/signupmodel.dart';

class GetCategory {
  List<Categories> category = [];

  Future<void> getCategory() async {
    var url = Uri.parse(Endpoints.BASE_URL + Endpoints.CATEGORIES);
    var response = await http.get(url);

    var jsonData = jsonDecode(response.body);
    category.add(Categories(name: "  All  ", slug: "All", id: 1));

    jsonData.forEach((cate) {
      Categories _cat = Categories(
        name: cate['name'],
        slug: cate['slug'],
        id: cate['id'],
      );
      category.add(_cat);
    });
  }

  List<Autogenerated> list = [];

  Future<void> getProducts() async {
    var url = Uri.parse(
        'https://onlinefruitsandvegetables.com/wp-json/wc/v3/products?consumer_key=ck_d9cbd5ce0299e60a0856425310447138687a35f2&consumer_secret=cs_badcff4c893a2f458ca2b874e177d25692439a38');

    var response = await http.get(url);
    var data = json.decode(response.body);
    var rest = data as List;
    print(list);
    list = rest
        .map<Autogenerated>((json) => Autogenerated.fromJson(json))
        .toList();
  }
}

class ApiHelper {
  Future<bool> createCustomer(CustomerModel model) async {

    bool ret = false;
    var jsn = jsonEncode(model);
    var url = Uri.parse("${Endpoints.singup}&email=${model.email.trim()}&password=${model.password}&last_name=${model.lastName}&first_name=${model.firstName}");
     SignupModel signupModel;
    var response = await http.post(url);
    var jsonData = jsonDecode(response.body);

    print("res    =====>>>>"+response.body.toString());
    if (response.statusCode == 201) {
      final signupModel = SignupModel.fromJson(jsonData);
      setUser(signupModel);

      print("ress    =====>>>>"+signupModel.email.toString());
      ret = true;
    }


    return ret;
  }
  Future<void> addtocartProducts(String id, String quant) async {
    var url = Uri.parse(
        'https://onlinefruitsandvegetables.com/wp-json/wc/store/v1/cart/add-item?consumer_key=ck_d9cbd5ce0299e60a0856425310447138687a35f2&consumer_secret=cs_badcff4c893a2f458ca2b874e177d25692439a38'+"?"+"id="+id+"&"+"quantity="+quant);
print("object"+url.toString());
    var response = await http.post(url);
    var data = json.decode(response.body);
    print("res    =====>>>>"+response.body.toString());
    var rest = data as List;
  // print(list);
  // list = rest
  //     .map<Autogenerated>((json) => Autogenerated.fromJson(json))
  //     .toList();
  }
  setUser(SignupModel model) async  {
    var sessionManager = SessionManager();
    if (model!=null){
      await sessionManager.set("name", model.firstName.toString()+" "+model.lastName.toString());
      await sessionManager.set("id", model.id);
      await sessionManager.set("email",model.email);
    }

  }
  Future<LoginResponseModel?> loginCustomer(
    String username,
    String password,
  ) async {
    LoginResponseModel? model;
    var authToken = base64.encode(
      utf8.encode(Endpoints.consumer_key + ":" + Endpoints.consumer_secret),
    );
    var response = await http.post(Uri.parse(Endpoints.token_url), body: {
      "username": username,
      "password": password,
    }, headers: {
      HttpHeaders.contentTypeHeader: "application/x-www-form-urlencoded",
      HttpHeaders.authorizationHeader: 'Basic $authToken',
    });
    var jsonData = jsonDecode(response.body);
    print("res    =====>>>>$jsonData");
    if (response.statusCode == 200) {
      var data = json.decode(response.body);

      model = data.map<Autogenerated>((json) => Autogenerated.fromJson(json));
      return model;
    }


  }

}

class GetProductFromCategory {
  List<Autogenerated> list = [];

  Future<void> getProductsFromCategory(String id) async {
    late Uri url;
    if (id == "1") {
      url = Uri.parse(
          'https://onlinefruitsandvegetables.com/wp-json/wc/v3/products?consumer_key=ck_d9cbd5ce0299e60a0856425310447138687a35f2&consumer_secret=cs_badcff4c893a2f458ca2b874e177d25692439a38');
    } else {
      url = Uri.parse(
          'https://onlinefruitsandvegetables.com/wp-json/wc/v3/products?consumer_key=ck_d9cbd5ce0299e60a0856425310447138687a35f2&consumer_secret=cs_badcff4c893a2f458ca2b874e177d25692439a38&category=$id');
    }
    var response = await http.get(url);
    var data = json.decode(response.body);
    var rest = data as List;
    print(list);
    list = rest
        .map<Autogenerated>((json) => Autogenerated.fromJson(json))
        .toList();
  }
}
